# Generated by Django 4.1.9 on 2023-05-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="lists.list"
            ),
        ),
    ]
